# Generated by Django 4.0.3 on 2022-03-14 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('site_type', models.CharField(choices=[('i', 'Ida'), ('v', 'Vuelta')], default='', help_text='Escoge el tipo de viaje', max_length=1)),
                ('origen', models.CharField(help_text='Introduce el nombre del origen', max_length=50, primary_key=True, serialize=False, verbose_name='Origen')),
                ('destino', models.CharField(help_text='Introduce el nombre del sitio', max_length=50, verbose_name='Destino')),
                ('time', models.TimeField(help_text='Introduce la hora de salida', verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('nombre', models.CharField(help_text='¡Escribe una canción que quieres que suene en la fiesta!', max_length=50, verbose_name='Canción')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única asociada a la canción', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.CreateModel(
            name='FechaDeBoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Introduce la fecha y hora de la boda', verbose_name='Fecha de la boda')),
            ],
            options={
                'verbose_name': 'Fecha de la boda',
                'verbose_name_plural': '_Fecha de la boda',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduce el nombre del evento (p.e Salida autobus Pamplona)', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Introduce una descripción para el evento', max_length=1000, verbose_name='Descripción del evento')),
                ('start_time', models.TimeField(help_text='Introduce la hora de inicio', verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, help_text='Introduce la hora de finalización', null=True, verbose_name='Hora fin')),
                ('location_name', models.CharField(blank=True, help_text='Introduce el nombre de la localización', max_length=50, verbose_name='Nombre localización')),
                ('location_url', models.URLField(blank=True, default='', help_text='Introduce el enlace a google maps', max_length=2000, verbose_name='Enlace a Google Maps')),
                ('image', models.URLField(default='', help_text='Introduce el enlace de la fotografía', max_length=2000, verbose_name='Enlace a la imagen')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'Itinerario',
            },
        ),
        migrations.CreateModel(
            name='ItinerarioHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Este es el texto que aparecerá en la página principal', max_length=20, verbose_name='Nombre header')),
                ('description', models.CharField(help_text='Esta es la descripcion que aparecerá debajo del título en la página principal', max_length=150, verbose_name='Descripcion header')),
            ],
            options={
                'verbose_name': 'Titulo Itinerario',
                'verbose_name_plural': '_Titulo Itinerario',
            },
        ),
        migrations.CreateModel(
            name='LugarDeLaBoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Este es el texto que aparecerá en la página principal', max_length=40, verbose_name='Lugar de la boda')),
                ('mensaje', models.CharField(help_text='Este es el texto que aparecerá en la página principal p.e."¡Estás invitado a la boda!" ', max_length=100, verbose_name='Mensaje')),
                ('location_url', models.URLField(blank=True, default='', help_text='Introduce el enlace a google maps', max_length=2000, verbose_name='Enlace a Google Maps')),
            ],
            options={
                'verbose_name': 'Lugar de la boda',
                'verbose_name_plural': '_Lugar de la boda',
            },
        ),
        migrations.CreateModel(
            name='NombresPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novio', models.CharField(help_text='Introduce el nombre del novio', max_length=50, verbose_name='Nombre novio')),
                ('novia', models.CharField(help_text='Introduce el nombre de la novia', max_length=50, verbose_name='Nombre novia')),
                ('descripcion_novio', models.TextField(blank=True, default='', help_text='Introduce descripción del novio (déjalo en blanco si no quieres que aparezca nada)', max_length=400, verbose_name='Descripción novio')),
                ('descripcion_novia', models.TextField(blank=True, default='', help_text='Introduce descripción de la novia (déjalo en blanco si no quieres que aparezca nada)', max_length=400, verbose_name='Descripción novia')),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': '_Nombres pareja',
            },
        ),
        migrations.CreateModel(
            name='WebPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Introduce la contraseña para el sitio web', max_length=50, verbose_name='Contraseña')),
                ('is_required', models.BooleanField(default=False, help_text='¿Quieres que la web tenga contraseña?', verbose_name='Activada')),
            ],
            options={
                'verbose_name': 'Contraseña',
                'verbose_name_plural': 'Contraseña Global',
            },
        ),
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID única asociada a la confirmación', primary_key=True, serialize=False)),
                ('asistiras', models.BooleanField(choices=[(None, ''), (True, '¡Sí!, contad conmigo'), (False, 'No voy a poder asistir')], default=None, help_text='¿Asistirás?', verbose_name='Asistirás')),
                ('time', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Introduce tu nombre', max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Introduce tu apellido', max_length=50, verbose_name='Apellido')),
                ('bus_ida', models.BooleanField(default=False, help_text='¿Necesitarás autobús de ida?', verbose_name='Autobús de ida')),
                ('bus_vuelta', models.BooleanField(default=False, help_text='¿Necesitarás autobús de vuelta?', verbose_name='Autobús de vuelta')),
                ('acompanantes', models.CharField(choices=[('0', 'Iré solo'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', help_text='Número de acompañantes', max_length=1, verbose_name='Número')),
                ('nombres_acompanantes', models.TextField(blank=True, help_text='Escribe los nombres de los acompañantes, uno por línea.', max_length=500, null=True, verbose_name='Información acompañantes')),
                ('food_restrictions', models.BooleanField(default=False, help_text='¿Tienes especificaciones alimentarias? (Alergias, vegetariano, no como carne...)', verbose_name='Alergias alimentarias / Otros')),
                ('food_restrictions_especificaciones', models.TextField(blank=True, default='', help_text='Especifica, en caso de tener acompañante, quién tiene la alergia/otro (Por ejemplo: "Ana no come carne")', max_length=500, verbose_name='Alergias alimentarias / Otros')),
                ('cancion', models.ForeignKey(blank=True, help_text='¡Introduce una canción que quieres que suene durante la fiesta!', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boda.cancion', verbose_name='Canción y grupo')),
            ],
            options={
                'verbose_name': 'confirmación',
                'verbose_name_plural': 'Confirmaciones',
            },
        ),
    ]
