# Generated by Django 4.0.3 on 2022-03-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmacion',
            old_name='id',
            new_name='_id',
        ),
    ]
