# Generated by Django 4.0.3 on 2022-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boda', '0002_rename_id_confirmacion__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobus',
            name='site_type',
            field=models.CharField(choices=[('i', 'Ida'), ('v', 'Vuelta')], default='', help_text='Escoge el tipo de viaje', max_length=1, verbose_name='Tipo de viaje'),
        ),
    ]
