# Generated by Django 4.0.3 on 2022-03-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boda', '0003_alter_autobus_site_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='cancion',
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nombre_cancion',
            field=models.TextField(blank=True, help_text='¡Introduce una canción que quieres que suene durante la fiesta!', max_length=50, null=True, verbose_name='Canción y grupo'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='nombre_grupo',
            field=models.TextField(blank=True, help_text='¡Introduce el grupo de la canción que quieres que suene durante la fiesta!', max_length=50, null=True, verbose_name='Canción y grupo'),
        ),
    ]
