# Generated by Django 4.0.3 on 2022-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boda', '0004_remove_confirmacion_cancion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacion',
            name='nombre_cancion',
            field=models.CharField(blank=True, help_text='¡Introduce una canción que quieres que suene durante la fiesta!', max_length=50, null=True, verbose_name='Canción y grupo'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='nombre_grupo',
            field=models.CharField(blank=True, help_text='¡Introduce el grupo de la canción que quieres que suene durante la fiesta!', max_length=50, null=True, verbose_name='Canción y grupo'),
        ),
    ]
